### ISSUE TITLE
뉴스 기사 제목

### ISSUE THREAD

**Issue by leeeeeoy** [affjljoo3581/canrevan#2]
안녕하세요. 먼저 좋은 자료 정말 감사합니다
s2s 기반의 nlp 학습프로젝트를 하고 있는데 혹시 해당 기사의 제목도 같이 끌어올 수 있을까요??

**Comment by affjljoo3581** [comment]
불가능합니다. 본 라이브러리는 [Format](https://github.com/affjljoo3581/langumo)에서 언급한 바와 같이 escaped된 string들을 line-by-line 형식으로 저장하고 있습니다. 기사 제목과 본문간의 구분이 불가능하여 현재 기사 본문만을 추출하여 정규화하고 있습니다.

**Comment by affjljoo3581** [comment]
만약 기사 제목이 필요하다면 직접 수정하는 것을 권장드립니다. 본 라이브러리를 git으로 clone한 후,

https://github.com/affjljoo3581/canrevan/blob/d0d9155fc768500acfc5c436f336415de8794f8e/src/canrevan/parsing.py#L34-L62

이 함수에서 제목과 본문을 함께 추출하도록 수정하시면 되겠습니다.

**Comment by leeeeeoy** [comment]
조언 감사합니다!
